version: '3'
services: # list of containers to create
  web:    # initial container / service
    build:  # specify image (dockerfile), . assumes there's a dockerfile
      context: . # where we want all the file and folders to be pulling from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules # do not try to map out a folder up against this folder
      - .:/app # map current folder to the app folder in container

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]